enable RUST_BACKTRACE to debug config load failure
the error message suggests a type error when config file is parsed by
get_configuration. however, serde-aux is installed and used
appropriately, so i have no idea what is going on...

[2024-05-04 18:30:27] thread 'main' panicked at src/main.rs:43:35:
[2024-05-04 18:30:27] called `Result::unwrap()` on an `Err` value: invalid digit found in string
[2024-05-04 18:30:27] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

the same error message is mentioned in this issue, but i don't see how
the reason (or its resolution) is relevant to my case:

https://github.com/LukeMathWalker/zero-to-production/issues/147